#!/bin/bash
# QUICK START: Run Enhanced Taxi Installer with Docker Permission Recovery
# This script now includes automatic detection and recovery for Docker permission issues

echo "═══════════════════════════════════════════════════════════════"
echo "  Taxi System Enhanced Installer (with Docker Permission Fix)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ Enhanced Features:"
echo "   • Automatic Docker permission detection"
echo "   • Interactive recovery menu if permission denied"
echo "   • Auto-fix: Add taxi user to docker group"
echo "   • Retry logic on Docker service startup"
echo ""
echo "📝 When prompted about Docker permissions:"
echo "   Select Option 1 to auto-fix (RECOMMENDED)"
echo "   This adds the 'taxi' user to the docker group"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Option 1: Download and run in one command (recommended for fresh installs)
echo "🚀 OPTION 1: One-liner (Fresh Install)"
echo "   Copy and paste this in your Ubuntu server terminal:"
echo ""
echo "   wget -q -O - https://raw.githubusercontent.com/Boris8800/Proyecto/main/install-taxi-system.sh | bash"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Option 2: Install to system command
echo "🚀 OPTION 2: System Command (Persistent)"
echo "   Make the installer available as system command:"
echo ""
echo "   sudo curl -L https://raw.githubusercontent.com/Boris8800/Proyecto/main/install-taxi-system.sh -o /usr/local/bin/taxi-install && sudo chmod +x /usr/local/bin/taxi-install"
echo ""
echo "   Then run anytime with:"
echo "   taxi-install"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Option 3: Using tmux for persistent session
echo "🚀 OPTION 3: Persistent Session (Handles Disconnects)"
echo "   If using SSH and worried about disconnects (e.g., PuTTY):"
echo ""
echo "   tmux new-session -d -s taxi-install 'wget -q -O - https://raw.githubusercontent.com/Boris8800/Proyecto/main/install-taxi-system.sh | bash | tee /var/log/install-taxi.log'"
echo ""
echo "   Monitor progress:"
echo "   tmux attach-session -t taxi-install"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Option 4: Manual download and run
echo "🚀 OPTION 4: Manual Download"
echo "   For more control over the installation:"
echo ""
echo "   curl -L https://raw.githubusercontent.com/Boris8800/Proyecto/main/install-taxi-system.sh -o install-taxi-system.sh"
echo "   chmod +x install-taxi-system.sh"
echo "   ./install-taxi-system.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Show expected prompts
echo "📋 What to Expect During Installation:"
echo ""
echo "   1. System package installation (Docker, Nginx, PostgreSQL, Redis)"
echo ""
echo "   2. Docker permission check:"
echo "      [WARN] Docker permission issue detected for user: taxi"
echo "      Options:"
echo "        1) Auto-fix: Add taxi to docker group (RECOMMENDED)"
echo "        2) Skip: Continue without fixing"
echo "        3) Exit: Stop installation"
echo ""
echo "      → Choose 1 (auto-fix is recommended)"
echo ""
echo "   3. Docker services starting:"
echo "      - PostgreSQL 15 (database)"
echo "      - Redis 7 (cache)"
echo "      - Node.js API (port 3000)"
echo "      - Admin panel (port 8080)"
echo ""
echo "   4. Installation complete:"
echo "      ✅ INSTALACIÓN COMPLETA"
echo "      🌐 API:         http://[YOUR_IP]:3000"
echo "      📊 Admin Panel: http://[YOUR_IP]:8080"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Verify endpoints
echo "✅ After Installation:"
echo ""
echo "   1. Check Docker containers running:"
echo "      docker ps"
echo ""
echo "   2. View API:"
echo "      curl http://localhost:3000"
echo ""
echo "   3. Check PostgreSQL:"
echo "      docker exec postgres15 psql -U admin -d taxi -c '\\dt'"
echo ""
echo "   4. View logs:"
echo "      tail -f /var/log/install-taxi.log"
echo "      tail -f /var/log/nginx/error.log"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Troubleshooting
echo "❌ If Something Goes Wrong:"
echo ""
echo "   Docker permissions still denied:"
echo "   → sudo usermod -aG docker taxi && newgrp docker"
echo ""
echo "   Port conflicts:"
echo "   → sudo fuser -k 80/tcp 443/tcp"
echo ""
echo "   Restart Docker services:"
echo "   → cd /home/taxi/app && sudo -u taxi docker-compose restart"
echo ""
echo "   Full reinstall:"
echo "   → docker system prune -a"
echo "   → ./install-taxi-system.sh"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "🎯 RECOMMENDED: Copy and paste Option 1 one-liner to start"
echo ""
